steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: [ 'install' ]
    options:
      logging: CLOUD_LOGGING_ONLY
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--tag=gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '.' ]
    options:
      logging: CLOUD_LOGGING_ONLY
images: [ 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}' ]